# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
  end

  config.vm.provider "hyperv" do |h|
    h.cpus = 2
    h.memory = 2048
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Install and configure iscsi
    yum -y install iscsi-initiator-utils

    echo "InitiatorName=iqn.2020-01.com.blachniet:initiator01" > /etc/iscsi/initiatorname.iscsi

    sed -i 's/^#node.session.auth.authmethod = CHAP/node.session.auth.authmethod=CHAP/' /etc/iscsi/iscsid.conf
    sed -i 's/^#node.session.auth.username =.*$/node.session.auth.username = username/' /etc/iscsi/iscsid.conf
    sed -i 's/^#node.session.auth.password =.*$/node.session.auth.password = password/' /etc/iscsi/iscsid.conf

    systemctl start iscsid
    systemctl enable iscsid

    # Install docker
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    usermod -aG docker vagrant
    systemctl start docker.service
    systemctl enable docker.service

    # Configure iptables for kubeadm
    # https://github.com/kubernetes/kubeadm/issues/312#issuecomment-309539056
    echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

    # Install minikube
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
      && chmod +x minikube
    mkdir -p /usr/local/bin/
    install minikube /usr/local/bin/

    # Start minikube
    /usr/local/bin/minikube start --vm-driver=none

    # Install kubectl
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    mv ./kubectl /usr/local/bin/kubectl

    # Allow vagrant to use kubectl
    # https://github.com/kubernetes/kubernetes/issues/44665#issuecomment-295216655
    mkdir -p /home/vagrant/.kube
    cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config
  SHELL
end
